[package]
name = "iot-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["full"] }
csv = { version = "1.3" }
serde_json = "1.0"
clap = { version = "4.5.8", features = ["derive"] }
dashmap = "6.0.1"
once_cell = "1.19"
chrono = "0.4.38"
sysinfo = "0.31.2"
bytes = "1.6.1"
serde_yaml = "0.9.33"
comfy-table = "7.1.1"
anyhow = "1.0.86"
tracing = { version = "0.1.40"}
tracing-subscriber = { version = "0.3.18"}
tempfile = "3"
hex = "0.4.3"

[build-dependencies]
fs_extra = "1.2"
